# Theme
theme: jekyll-theme-cayman

# Plugins
plugins:
- jekyll-remote-theme

# Basic site information
title: NaFi
description: My small open-source cheatsheet on finance.
show_downloads: false

kramdown:
  parse_block_html: true
  parse_span_html: true